# Generated by Django 4.1 on 2024-06-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stud_fname', models.CharField(max_length=30, null=True)),
                ('stud_lname', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myAPI.school')),
            ],
        ),
    ]
