# Generated by Django 4.1 on 2024-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_school_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapp',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
